spring:
  datasource:
    url: ${PGSQL_JDBC_URL:jdbc:postgresql://postgredb:5432/cabdb?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false}
    username: ${PGSQL_USERNAME:def_user}
    password: ${PGSQL_PASSWORD:pass}
  kafka:
    bootstrap-servers: broker:29092
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/taxi-realm/protocol/openid-connect/certs
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/